spring:
  config.activate.on-profile: local, test, dev
  cloud:
    discovery:
      enabled: false

    config:
      allow-override: false
---
spring:
  config.activate.on-profile: prd

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-app:19090/eureka/

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
