spring:
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
---
