spring:
  config:
    import:
      - classpath:properties/server.yml
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/flyway.yml
      - classpath:properties/pg.yml
      - classpath:properties/eureka.yml
      - classpath:properties/feign.yml
      - classpath:properties/microservice-registry.yml
      - classpath:properties/wiremock.yml
      - classpath:properties/feature-flag.yml
      - classpath:properties/logging.yml
  profiles:
    active: dev
