name: Develop CI

env:
  MODULE_NAME: payment-app
  BUILD_ID: ${{ github.sha }}
  REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_NAME }}
on:
  push:
    branches: [ "deploy" ]

jobs:
  build:
  runs-on: ubuntu-latest
  environment: production

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: aws-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      run: |
        ./gradlew jibDockerBuild
        docker tag $MODULE_NAME $REGISTRY/$REPOSITORY:$BUILD_ID
        docker push $REGISTRY/$REPOSITORY:$BUILD_ID            
