# @name 결제 요청
GET http://localhost:8080/checkout
    ?customerId=80
    &couponId=new-coupon80
    &concertId=concert-a
    &seatIds=1
Content-Type: application/json

###
# @name 쿠폰 없는 결제 요청
GET http://localhost:8080/checkout
    ?customerId=81
    &concertId=concert-81
    &seatIds=1
Content-Type: application/json
