# @name 결제 요청
GET http://localhost:8080/checkout
    ?customerId=31
    &couponId=new-coupon31
    &concertId=concert-a
    &seatIds=1
Content-Type: application/json

###
# @name 쿠폰 없는 결제 요청
GET http://localhost:8080/checkout
    ?customerId=32
    &concertId=concert-a
    &seatIds=1
Content-Type: application/json
